name: Terraform

on:
  push:
    branches: [master]
    paths: ['terraform/**', '.github/workflows/terraform.yml', 'lambda/**']
  pull_request:
    branches: [master]
    paths: ['terraform/**', '.github/workflows/terraform.yml', 'lambda/**']
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  terraform:
    uses: Xomware/github-actions/.github/workflows/terraform.yml@v1
    with:
      app: xomper
      terraform-version: "1.10.5"
